### ISSUE TITLE
Firebase In-App Messaging

### ISSUE THREAD

**Issue by oarsheo** [wizpanda/cordova-plugin-firebase-lib#19]
Please add Firebase In-App Messaging functionality
https://firebase.google.com/docs/in-app-messaging/get-started?authuser=0&platform=android

https://www.youtube.com/watch?v=5MRKpvKV2pg

**Comment by torsorensen** [comment]
> Please add Firebase In-App Messaging functionality
> https://firebase.google.com/docs/in-app-messaging/get-started?authuser=0&platform=android
> 
> https://www.youtube.com/watch?v=5MRKpvKV2pg

It's already in? I'm using it on a daily basis.

**Comment by sagrawal31** [comment]
Have you checked https://github.com/chemerisuk/cordova-plugin-firebase-inappmessaging? The author is active and the repository is already being maintained.
