### ISSUE TITLE
Android build failure

### ISSUE THREAD

**Issue by brad426** [wizpanda/cordova-plugin-firebase-lib#20]
## Describe the bug

After adding this plugin, my Android build fails with the following message:
```
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver
```

Cordova version: **9.0.0** (cordova-lib@9.0.1)
cordova-android version: **8.0.0**

Plugins:
 - card.io.cordova.mobilesdk 2.1.0 "CardIO"
 - cordova-plugin-apprate 1.4.0 "AppRate"
 - cordova-plugin-appsflyer-sdk 4.4.15 "AppsFlyer"
 - cordova-plugin-compat 1.2.0 "Compat"
 - cordova-plugin-device 2.0.2 "Device"
 - cordova-plugin-dialogs 2.0.1 "Notification"
 - cordova-plugin-facebook4 4.2.1 "Facebook Connect"
 - cordova-plugin-firebase-lib 4.0.1 "Google Firebase Plugin"
 - cordova-plugin-geolocation 2.4.3 "Geolocation"
 - cordova-plugin-geolocation-permission-status 1.0.0 "Cordova Plugin Geolocation Permission Status"
 - cordova-plugin-globalization 1.11.0 "Globalization"
 - cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
 - cordova-plugin-nativestorage 2.3.2 "NativeStorage"
 - cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
 - cordova-plugin-splashscreen 5.0.2 "Splashscreen"
 - cordova-plugin-statusbar 2.4.2 "StatusBar"
 - cordova-plugin-whitelist 1.3.3 "Whitelist"

If I downgrade cordova-android to 7.0.0 the app builds successfully, but I get runtime errors because `window.FirebasePlugin` is undefined

Any ideas about how to resolve would be greatly appreciated.

**Comment by sagrawal31** [comment]
Can you try running:

```bash
cordova plugin add cordova-plugin-androidx
cordova plugin add cordova-plugin-androidx-adapter
```

**Comment by brad426** [comment]
@sagrawal31 Yup, that fixed it. Building successfully now. Thank you very much!
Struggling to test on an emulator now - Android studio build fails with error:
```
ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Move minSdkVersion to build files and sync project
Affected Modules: CordovaLib, app
```

But i'm sure that's something I can sort out myself

**Comment by brad426** [comment]
Android studio auto refactored the project sorting out the minSdk issue, and the plugin is working perfectly now.
