### ISSUE TITLE
Module 'FirebaseInstanceID' not found

### ISSUE THREAD

**Issue by alvaro-octal** [wizpanda/cordova-plugin-firebase-lib#25]
## Describe the bug

iOS xcode build is failing due to FirebaseInstanceID is missing.

## To Reproduce

1. Installed the plugin, added platform, no errors.
2. Did `pod install` & `pod update`, no efect.
3. Tried to run the app on iPhone.
4. Build failed.

## Expected behavior

Project should build.

## Screenshots

<img width="706" alt="Captura de pantalla 2019-06-25 a las 11 11 21" src="https://user-images.githubusercontent.com/4562922/60085817-4ac78d80-973a-11e9-83ad-45a742ea4732.png">

## Console Logs

```
Module 'FirebaseInstanceID' not found
```

## Plugin Version

```
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-background-geolocation-lt 3.0.7 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.5.0 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase-lib 5.0.0 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.2 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

## Desktop (please complete the following information):

- OS: Mac OS 10.14.5
- Xcode: 10.2.1
- Pods: 1.7.2

## Smartphone (please complete the following information):

Irrelevant

## Additional context

No addition context, I guess.

BTW, thanks for your work, seems promising.

**Comment by sagrawal31** [comment]
Can you please confirm the version of `cordova-cli` and `cordova-ios`?

**Comment by alvaro-octal** [comment]
Hi @sagrawal31,

I'm using cordova-cli 9.0.0 and installed cordova-ios 5.0.1

**Comment by geoox** [comment]
I'm experiencing the same issue:

ionic info:
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/Users/georgedobrin/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 14 other plugins)

System:

   ios-sim : 8.0.1
   NodeJS  : v10.15.3 
   npm     : 6.4.1
   OS      : macOS Mojave
   Xcode   : Xcode 10.1 Build version 10B61

**Comment by sagrawal31** [comment]
Use [v5.1.0](https://github.com/wizpanda/cordova-plugin-firebase-lib/releases/tag/v5.1.0) to make it work. Make sure you have at least `1.5.0` of Cocoapod installed. Please reopen the issue if you are still getting an error due to this plugin.
