### ISSUE TITLE
Option to receive push notification when app is killed

### ISSUE THREAD

**Issue by eeerrrttty** [wizpanda/cordova-plugin-firebase-lib#3]
Here on my android, i doesn't receive push notifications when app is killed / closed, just on background. How can this be solved ?

**Comment by sagrawal31** [comment]
We are using this library in our 3 productions apps and seems to work fine. Are you expecting to receive data payload based notifications (where there is no title & body)?

**Comment by Dec-** [comment]
What version of Android do you have?

**Comment by sagrawal31** [comment]
@eeerrrttty were you able to get this working? Because this fork is working for us in our two production applications.

**Comment by sunhuafeng1992** [comment]
I also had the same problem on ios12. I couldn't receive notification when I was running in the background, but I was notified when I was running in the front desk, hoping to get a reply.

**Comment by leodiano** [comment]
test on another phone, if it works, reset your device's messaging settings

**Comment by sagrawal31** [comment]
@eeerrrttty I'm closing this issue assuming things are working now for you. Please feel free to re-open later if this is not the case.
