### ISSUE TITLE
I don't seem to find a way to use this plugin in ionic 4

### ISSUE THREAD

**Issue by JoseGeorges8** [wizpanda/cordova-plugin-firebase-lib#40]
I Can't use @ionic-native/firebase integration for ionic 4 since the integration looks for the original cordova-plugin-firebase package. I tried using the window object and declaring the name of the plugin globally, but none of them work for me

Any suggestions? Thanks!

These are my dependencies:

```
Ionic:
   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 22 other plugins)

plugins:

    "@ionic-native/firebase": "^4.20.0",
    "cordova-plugin-firebase-lib": "^5.1.1",

```

**Comment by sagrawal31** [comment]
Have you tried using the `@ionic-native/firebase`? It should work because the variable used by this plugin is same so that should not conflict.

**Comment by JoseGeorges8** [comment]
If you read the very first line of my comment it says that I did tried using that integration, however I solved the problem by downgrading the plugin version to 4.1.0. Now it doesn't conflict and can use with the `@ionic-native/firebase`
