### ISSUE TITLE
Plugin not installed

### ISSUE THREAD

**Issue by mustafabekec** [wizpanda/cordova-plugin-firebase-lib#43]
I did the following operations respectively. But I get the plugin not installed.
How can I solve this problem?

`ionic cordova platform rm android `
`cordova plugin remove cordova-plugin-firebase`
`cordova plugin add cordova-plugin-firebase-lib`
`ionic cordova plugin add cordova-plugin-androidx`
`ionic cordova plugin add cordova-plugin-androidx-adapter`
`ionic cordova run android`

[Link](https://forum.ionicframework.com/t/build-break-with-aapt-error-message-why/123955/14)

![hata1](https://user-images.githubusercontent.com/7298988/61318155-13b23c80-a80d-11e9-9ff2-1d736eecdd19.PNG)

**Comment by sagrawal31** [comment]
Can you please follow the checklist which you have seen while creating the issue. It's hard for us to know the environment of the issue author.

**Comment by mustafabekec** [comment]
> Can you please follow the checklist which you have seen while creating the issue. It's hard for us to know the environment of the issue author.

I don't know exactly what you mean. If you can give me a more specific answer, I will do what I have to do. Excuse me. Thank you.

**Comment by sagrawal31** [comment]
On a quick note, you must be using an old version of `ionic-cli`. Also, since you are using Ionic, instead of `cordova plugin add cordova-plugin-firebase-lib`, you need to do `ionic cordova plugin add cordova-plugin-firebase-lib`. So do the following steps:

```
cordova plugin remove cordova-plugin-firebase-lib
ionic cordova plugin add cordova-plugin-firebase-lib
```

**Comment by sagrawal31** [comment]
> > Can you please follow the checklist which you have seen while creating the issue. It's hard for us to know the environment of the issue author.
> 
> I don't know exactly what you mean. If you can give me a more specific answer, I will do what I have to do. Excuse me. Thank you.

When you have started raising this issue, you must have seen this template https://github.com/wizpanda/cordova-plugin-firebase-lib/issues/new?template=bug_report.md. Before debugging an issue, the repository author needs to know about the system environment of the reporter. That will definitely help us to help you 😄

**Comment by sagrawal31** [comment]
@mustafabekec did that worked?

**Comment by mustafabekec** [comment]
> @mustafabekec did that worked?

[That was exactly my problem](https://forum.ionicframework.com/t/build-break-with-aapt-error-message-why/123955)

## ionic info

Ionic:

   Ionic CLI          : 5.2.3 (C:\Users\Meftun\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.1

Cordova:

   Cordova CLI       : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 19 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.7

System:

   Android SDK Tools : 26.1.1 (C:\Users\Meftun\AppData\Local\Android\sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.10.0
   OS                : Windows 10
   
## The solution

1. `npm uninstall -g cordova`
2. `npm cache clean --force`
3. `npm i -g cordova@8.1.1`

4. `ionic cordova platform rm android`
5. `cordova plugin remove cordova-plugin-firebase`
6. `cordova plugin add cordova-plugin-firebase-lib@4.1.0 --save`
7. `ionic cordova plugin add cordova-plugin-androidx`
8. `ionic cordova plugin add cordova-plugin-androidx-adapter`
9. `ionic cordova platform add android@8.0.0`
19. `cordova run android`

It worked that way. That was the first problem I had in Github. So I'm sorry for the wrong format. Thank you so much for your support!

**Comment by mustafabekec** [comment]
> @mustafabekec did that worked?

@sagrawal31 
Why doesn't this extension add the firebase folder to node_modules\@ionic-native? That's why I'm getting errors now. It's about Firebase.

## Screenshots
![hata17072019 3](https://user-images.githubusercontent.com/7298988/61363353-89a9b880-a88c-11e9-8310-9b0878c6e397.PNG)


![hata17072019](https://user-images.githubusercontent.com/7298988/61363452-b2ca4900-a88c-11e9-887e-0ea027500e3e.PNG)


> node_modules\@ionic-native folder

![error 2](https://user-images.githubusercontent.com/7298988/61360581-64ff1200-a887-11e9-9e77-ebad3bc5d942.PNG)


Normally when we install [this Firebase extension](https://ionicframework.com/docs/v3/native/firebase) it adds firebase to the node_modules\@ionic-native directory. But that does not add?

I think the problem will be solved when you add firebase to this directory. How can I do this with your plugin? Help me please..

**Comment by sagrawal31** [comment]
Ionic is not related to this plugin. It's (`@ionic-native/firebase@4`) just a typescript wrapper to use the API of this plugin in Angular/Ionic code. So you must be adding the wrong version of that wrapper. Please try installing `@ionic-native/firebase@4`.

Closing this issue considering the issue not related to this Cordova plugin. Feel free to reopen if you have a direct issue with this plugin.
