### ISSUE TITLE
Livereload not working

### ISSUE THREAD

**Issue by mariusbolik** [wizpanda/cordova-plugin-firebase-lib#46]
Hello,

I can't compile my app using the --livereload flag. The build progress seems to stuck at a certain point.
This is the command I'm using:
`ionic cordova run ios --livereload`

I'm using the Ionic CLI 4.12.0, because Version 5.X is really buggy and it's using the npm package "native-run" which doesn't seem to work very well.

Does someone else has this problem with Ionic?

Best Regards
Marius

**Comment by sagrawal31** [comment]
Please raise an issue (with a detailed description) in Ionic repos. Ionic is not directly related to this Cordova plugin.
