### ISSUE TITLE
iOS fails to build, says API key not valid

### ISSUE THREAD

**Issue by distinctdan** [wizpanda/cordova-plugin-firebase-lib#6]
**Describe the bug**
iOS is failing to build for me. Here's the error I'm getting:
```
2019-06-05 16:31:39.209 uploadDSYM[6583:121355] Fabric.framework/run 1.7.1 (209)
error: Fabric: Configuration Issue

Fabric API key not valid. Your Fabric run script build phase should contain your API key:
./Fabric.framework/run INSERT_YOUR_API_KEY INSERT_YOUR_BUILD_SECRET
```

**However**, the firebase docs said that you should put your GoogleService-Info.plist into your app's root directory. This plugin copies it to the Resources folder instead. So, I manually dragged the file to the root directory, and that fixed the build. But, when I dragged it back to the Resources folder, the build continued to work, so I'm not sure why that fixed it.

**To Reproduce**
1. Install the plugin.
2. Download GoogleService-Info.plist into my cordova root directory.
3. Build.

**Comment by distinctdan** [comment]
After removing/readding the platform and plugin, it's still continuing to work, so I'm not sure why it wasn't working before.

**Comment by sagrawal31** [comment]
That might be because of the old firebase plugin existed in the `plugins` or `platforms` directory.
